service: ictb-sls

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
        - "s3:DeleteObject"
      Resource: arn:aws:s3:::sainos-bucket/*
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: !GetAtt drinksTable.Arn

functions:
  drinksDynamoImport:
    handler: drinks.import_drinks
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - s3: 
          bucket: sainos-bucket
          event: s3:ObjectCreated:Put  
          rules:
            - prefix: transactions/
            - suffix: .csv
          existing: true
  auto_etl:
    handler: ictb-etl.auto_etl
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    # events:
    #   - s3: 
    #       bucket: sainos-bucket
    #       event: s3:ObjectCreated:Put  
    #       rules:
    #         - prefix: transactions/
    #         - suffix: .csv
    #       existing: true
    environment:
      DB_USER2: "${self:custom.DB_USER2}"
      DB_PW2: "${self:custom.DB_PW2}"
      DB_HOST2: "${self:custom.DB_HOST2}"
      DB_NAME2: "${self:custom.DB_NAME2}"
 
plugins:
  - serverless-python-requirements
custom:
  DB_USER2: admin
  DB_PW2: zA8bnZeg7huCIKnLgXfEqq3c
  DB_HOST2: cafe-poc.cqohmuwgawul.eu-west-1.rds.amazonaws.com
  DB_NAME2: poc_data
  pythonRequirements:
    dockerizePip: non-linux
    layer: true  #Put dependencies into a Lambda Layer.
    slim: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - numpy
  
package:
  exclude:
    - venv/** 
    - node_modules/** 
    - model/** 
    - .vscode/** 
    - __pycache__/** 
    - .idea/**

resources:
  Resources:
    drinksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: drinksTable
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
          - AttributeName: _rng
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
          - AttributeName: _rng
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST